import 'package:drift/drift.dart';
import 'package:drift/wasm.dart';
import 'package:flutter/services.dart' show rootBundle;

/// web/sqlite3.wasm and web/drift_worker.js are prebuilt binaries matching
/// the exact sqlite3/drift package versions in pubspec.lock (see
/// tool/data/README.md-style provenance note in HANDOFF.md) — they are not
/// generated by this repo's own build.
Future<QueryExecutor> openConnection() async {
  final result = await WasmDatabase.open(
    databaseName: 'bible',
    sqlite3Uri: Uri.parse('sqlite3.wasm'),
    driftWorkerUri: Uri.parse('drift_worker.js'),
    initializeDatabase: () async {
      final data = await rootBundle.load('assets/bible.db');
      return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    },
  );
  return result.resolvedExecutor;
}
